[package]
name = "naga-xtask"
version = "0.1.0"
edition = "2021"
publish = false
rust-version = "1.84"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
anyhow.workspace = true
env_logger = { workspace = true, default-features = false }
glob.workspace = true
hlsl-snapshots.workspace = true
indicatif.workspace = true
jobserver.workspace = true
log.workspace = true
num_cpus.workspace = true
pico-args.workspace = true
shell-words.workspace = true
which.workspace = true
